### ISSUE TITLE
bug report, 

### ISSUE THREAD

**Issue by ghost** [halcy/MastodonToTwitter#1]
![image](https://cloud.githubusercontent.com/assets/23704040/20637645/d8ea9d70-b35b-11e6-9d32-35e8c674b7a8.png)
failed on this toot: https://mastodon.social/users/hoodie/updates/225175

**Comment by halcy** [comment]
Thank you for the bug report.

How weird. I'd rather it'd be a bug in my own code that I can fix immediately, but at a glance, it seems like a problem with the underlying library... I can't immediately reproduce it, anyways.

Yours package is from from dist-packages, so probably installed via the system package manager. Can you try doing 

apt-get remove python-twitter 

followed by 

pip3 install python-twitter

to pull the newest version, and then try again? If it's not that, I'll have to see where else the bug could be (but if I was passing in a tuple or whatever, it should explode _way_ earlier... it's a bit weird. I'll look at my code to see if there is anywhere one could drop out.)

**Comment by ghost** [comment]
thank you for this! i reinstalled and haven't had this issue yet today, but ill shoot off a bug report when it does if it does

**Comment by halcy** [comment]
Alright. I'll meanwhile make a note that python version 3.4 minimum is required (didn't realize html.unescape is 3.4 upwards only)

**Comment by THE-ORIGINAL-MASTER** [comment]
How much total for all bugs today

**Comment by THE-ORIGINAL-MASTER** [comment]
I mean if you add them all up what is the total
