### ISSUE TITLE
App creation should be automatic... ... but it failed. 

### ISSUE THREAD

**Issue by thewesker** [halcy/MastodonToTwitter#11]
Have tried many times and this occurs every single time after entering in my Mastodon username and password:

App creation should be automatic...
... but it failed. That shouldn't really happen. Please retry
from the start, and if it keeps not working, submit a bug report at
http://github.com/halcy/MastodonToTwitter

Twitter verification works fine, but I am stuck on this.

**Comment by halcy** [comment]
That's weird. I wonder if the API for app creation changed - it might have. I'll look into it.

**Comment by tybritten** [comment]
It looks like the issue is in the timeout portion of mastodon.py

**Comment by halcy** [comment]
Fixed in Mastodon.py 1.0.4, so update that to fix things. Thank you!
