### ISSUE TITLE
Script crash if the mastodon acount has no toot

### ISSUE THREAD

**Issue by s18alg** [halcy/MastodonToTwitter#15]
I try to run the script on a brand new mastodon account.
It dies on line 195 because the index is out of range.
Posting a toot by hand is a quick workaround for now, but maybe base the start time on the current timestamp if there is no toot would be better ?

**Comment by notklaatu** [comment]
Also ran into this error. Submitted a simple fix.

**Comment by halcy** [comment]
Fixed by #20
