### ISSUE TITLE
What about choosing the way you want the crosspost?

### ISSUE THREAD

**Issue by jrmgx** [halcy/MastodonToTwitter#17]
For example, because you have configured both app,
you should be able to choose if you want to cross post from Mastodon to Twitter
or from Twitter to Mastodon
IMHO the second will allow more people to get in Mastodon as for now the network effect is still more powerful on Twitter

**Comment by halcy** [comment]
Hi! As is, the cross-poster posts both ways, twitter to mastodon and mastodon to twitter (initially it was one way, thus the name). There's a PR currently with code that would allow you to turn one or the other way off, #16

**Comment by jrmgx** [comment]
Interesting :) 
It could be nice to make this behaviour more clear in the doc because I didn't get it and I think it is a good point to highlight!

**Comment by s18alg** [comment]
Hi !
I have a new idea that I will work on soon. I'll update the documentation at the same time.
I would like to know if my variable name aren't clear enough.

**Comment by halcy** [comment]
Maybe picking should just be part of the config process (and the instance, also), that would be a bit more user-friendly.

**Comment by s18alg** [comment]
If we go that way, we should do a separated config file for those information.
