### ISSUE TITLE
Script crashes on utf8

### ISSUE THREAD

**Issue by wxcafe** [halcy/MastodonToTwitter#18]
I don't know what triggers it, but it seems this script chokes on UTF-8 toots (and probably on UTF-8 tweets too) 

<img width="1162" alt="screen shot 2017-04-04 at 20 58 16" src="https://cloud.githubusercontent.com/assets/3009327/24673790/c62e25c4-1979-11e7-90d7-08b1e095cf16.png">

**Comment by halcy** [comment]
Would that be outputting to a file or log rather than stdout? I believe what's happening is that python detected that you're outputting to something that cannot handle utf-8 (or that it thinks cannot handle utf-8).

**Comment by wxcafe** [comment]
That's logging to stdout, but since it runs in systemd it outputs to the system journal. So it should be utf8 capable

But yeah, it looks like you're right! This is weird. I'm gonna look at it a bit

EDIT : I investigated a bit but I've got no idea how to fix this, if you have a clue please weigh in.

**Comment by wxcafe** [comment]
Okay I found the fix : you need to put `Environment=LC_ALL=en_US.UTF-8` in the systemd service for it to work. Putting that into my pull request.

**Comment by halcy** [comment]
Thank you! I'm merging it. Still would like to figure out if this problem can't be avoided, though...
