### ISSUE TITLE
it seems to have happened again

### ISSUE THREAD

**Issue by ghost** [halcy/MastodonToTwitter#2]
![image](https://cloud.githubusercontent.com/assets/23704040/20641303/13e38272-b3c3-11e6-8fcc-71c93c02ccda.png)
this toot killed it: https://mastodon.social/users/hoodie/updates/233375

**Comment by ghost** [comment]
it seems to have something to do with URLs/Links

**Comment by halcy** [comment]
Hm. I think the problem is two-fold: One, I don't expand URLs that mastodon abbreviates for display properly (I can fix that easy) but also, python-twitter should not outright _crash_ due to this. I'm looking into it.

**Comment by ghost** [comment]
thank you for your efforts!!
