### ISSUE TITLE
Posting `<` or `>` on Twitter gets you `&lt;` and `&gt;` in Mastodon.

### ISSUE THREAD

**Issue by Spaxe** [halcy/MastodonToTwitter#24]
Posting on Twitter:

``` >>> stemgames.org.au <<< ```

Cross-posted to Mastodon by script:

``` &gt;&gt;&gt; https://www.stemgames.org.au/ &lt;&lt;&lt; ```

**Comment by gjorando** [comment]
Fixed it (PR #31 )

**Comment by halcy** [comment]
Fixed by #31
