### ISSUE TITLE
Retweets don't get posted to Mastodon

### ISSUE THREAD

**Issue by dejIO** [halcy/MastodonToTwitter#29]
I'm running the script as a systemd service. Any idea on what might be going wrong?

**Comment by halcy** [comment]
Retweets are not currently handled. I guess they could be handled by turning them into a link to the tweet, maybe (and vice-versa...).

**Comment by dejIO** [comment]
Fair enough. I was thinking something like:

`RT @jack (jack@twitter.com): Retweet goes here.`

Essentially parsing the retweet and making it into a normal tweet/toot.

**Comment by Mte90** [comment]
Will be very cool that feature

**Comment by AmauryCarrade** [comment]
The latest version supports this.
