### ISSUE TITLE
Toots that are unlisted or private should be ignored

### ISSUE THREAD

**Issue by denmojo** [halcy/MastodonToTwitter#34]
Great syncing tool, but unlisted and private toots should not get posted to Twitter. Luckily it is ignoring @Replies, but I suspect even direct toots are pushed to Twitter if they do not lead off with a @mention

**Comment by halcy** [comment]
Hm. I feel like it should be configurable whether you want those to cross over (Maybe even, if you'd want to get fancy, have different accounts for them?), but by default, they definitely should not get crossposted. Good catch.
