### ISSUE TITLE
Configuration should happen inside docker

### ISSUE THREAD

**Issue by fwenzel** [halcy/MastodonToTwitter#35]
I have a Debian system with Python 3.2 and no super easy way to update to Python 3.4, but that's okay because this is Dockerized and that'll install everything I need.

Except to configure the script, I need to install Python 3.4 after all, which is a bit silly.

Any way to run the configuration inside the container?

**Comment by halcy** [comment]
I'm not sure how docker works, but usually, configuration happens on first run of the script.

**Comment by fwenzel** [comment]
That's fine -- the instructions should then have the first run of the script happen *inside* Docker, else you're installing all dependencies on the Host first, and *then* create a docker container that installs all of the dependencies again, this time inside.
