### ISSUE TITLE
"Encountererd error. Not retrying."

### ISSUE THREAD

**Issue by dblicken** [halcy/MastodonToTwitter#6]
As you saw, this works great for me. I see that replies are exempt from xposting by design and I may have a bug (or I don't understand):

Found new toots, processing:
Toot bigger 140 characters, need to split...
new part
Tweeting " A second test of https://github.com/halcy/MastodonToTwitter (programmatically crosspost to Twitter from Mastodon) because I don't understand the --"...
Encountererd error. Not retrying.
Finished toot processing, resting until next toots.

**Comment by halcy** [comment]
The first thing is by design (assuming twitter user names and mastodon user names will be different) and should be explained in the README.

The second thing is a bug - this is a problem with the tweet length calculation, that I can probably fix.

**Comment by dblicken** [comment]
....and "Encountererd" is a typo. :)

**Comment by dblicken** [comment]
In case it helps, another:

Found new toots, processing:
Toot bigger 140 characters, need to split...
new part
Tweeting " "Plymouth State lab builds on school’s transformation plans" http://www.washingtontimes.com/news/2016/nov/28/plymouth-state-lab-builds-on-schools-transformatio/ --"...
Encountererd error. Not retrying.
Finished toot processing, resting until next toots.
