### ISSUE TITLE
New lines are not sent to twitter

### ISSUE THREAD

**Issue by Aldarone** [halcy/MastodonToTwitter#8]
When putting new lines in a toot, Mastodon uses `<p>` tags which are stripped when sending the tweet.

- https://mastodon.social/users/Alda/updates/1162829
- https://twitter.com/WebScrewdriver/status/829372857062940674

I think one solution is to replace `</p><p>` with a new line before stripping the other html tags.

**Comment by halcy** [comment]
Yep, though I'd probably trigger on just </p> tags, no matter what is around them (more robust), anything you see that would speak against doing that?

**Comment by Aldarone** [comment]
I think the only tag used are `p` and `a` so it should be ok.

**Comment by gjorando** [comment]
I made a PR that fixes this issue.

**Comment by Spaxe** [comment]
#30

**Comment by halcy** [comment]
Fixed by #30
